feat: document first platform release 2023.11.10
input-output-hk/atala-releases pull request #15
Opened 2023-11-13 08:45 UTC by womfoo

2023-11-13 11:21 UTC, antonbaliasnikov commented
@womfoo , could you, please, clarify what this is about? This repository is only for Atala platform releases. I believe the platform release can be in the repository that is related to the code when it's released. Or you would like to combine some infra changes here? We can also include them into our main ecosystem release.

2023-11-13 11:29 UTC, womfoo commented
thanks for the review @antonbaliasnikov, the idea was to keep a logbook of the platform changes somewhere. Happy to make them inter the 2.6 release if it makes sense there (not sure since most of the platform changes are internal).

2023-11-14 09:38 UTC, mkbreuningIOHK requested changes

2023-11-14 09:38 UTC, mkbreuningIOHK commented on Atala Platform/2023.11.10.md
> +# Atala PRISM v2.5
Change to Atala Platform, I guess no versioning as it is by date.

2023-11-14 09:38 UTC, mkbreuningIOHK commented on Atala Platform/2023.11.10.md
> +- ArgoCD Slack Notifications - Deployments status are now sent to internal slack channel #atala-release-notifications
I would consider to add:
- a section that indicates what benefit the feature is adding
- a section that is asking the recipient of the release what is asked them to do with the new feature. Example on the environment dashboard, should the user click and connect to the dashboard and then what he/she can do with it? Same for the slack notification. Is there any feedback your are asking with this feature? (format of the info in the notification)
- a documentation section to this release template: if a user wants to know more about the added features, where to go

2023-11-14 10:00 UTC, milosbackonja approved these changes

2023-11-16 00:40 UTC, womfoo commented
moving this as releases at https://github.com/input-output-hk/atala-prism-v2-infra

2023-11-16 00:40 UTC, closed without merging